### PR TITLE
Fix inheritance issue causing a memory leak.

### LINKED ISSUE #518: Ever Increasing Memory Usage in PowerShell Universal
There is something weird happening with PowerShell Universal and PSFramework. I've been trying to nail it down but could use a second set of eyes. 

I have this script running every second in my environment. 

```
[PSFramework.Message.LogHost]::MaxMessageCount = 2;

$paramSetPSFLoggingProvider = @{
    Name         = 'logfile'
    InstanceName = 'script'
    FilePath     = 'C:\temp\log.csv'
    Enabled      = $true
}
Set-PSFLoggingProvider @paramSetPSFLoggingProvider

1..10 | % {
    Write-PSFMessage -Message 'Hello' -Level 'Critical'
}
```

I then am using this for debugging. 

```

[System.Management.Automation.Runspaces.Runspace]::DefaultRunspace.InstanceId

"Filters:"

[PSFramework.Filter.FilterContainer]::Filters.GetType().GetField("_Filters", [System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::NonPublic).GetValue($null).Values.Count

"RunspaceHost"

$field = [PSFramework.Runspace.RunspaceHost].GetField('_runspaceBoundValues', [System.Reflection.BindingFlags]'Static, NonPublic')
$field.GetValue($null).Count

"Runspace Bound Values"

$field.GetValue($null) | Select -First 1 | ForEach-Object {
    $_.Values.Count
    $_.Values | Select -First 1
}

"Script Blocks"

[PSFramework.Utility.UtilityHost]::ScriptBlocks.Count

"Log Queue:"

$field = [PSFramework.Message.LogHost].GetField('LogEntries', [System.Reflection.BindingFlags]'Static, NonPublic')
$queue = $field.GetValue([PSFramework.Message.LogHost])
$queue.Count
```

I see these runspaces in PSU. 

```
[Process:11280]: PS C:\Users\adamr\OneDrive\Documents> get-runspace | select instanceid

InstanceId
----------
286773b0-5544-4866-8fd7-72d82941c3c3
4ba204ac-2289-4af9-be77-c79cdf0374c3
bd2cb06f-0a10-4638-bbe7-5e5208e4e656
0100a85e-2044-4461-8524-74b48449e824
fd9782b4-d65c-42a7-93ff-6663daa47eac
cb0c535e-0020-4911-b789-1171e5f220e2
7fb0fec0-b584-4472-9b4a-3c72ded2d6fb
```

Running the script to output various collections out of PSF yields this. 

```
May 7, 2022 1:51 PM  Guid 
May 7, 2022 1:51 PM  ---- 
May 7, 2022 1:51 PM  06b29d3b-c387-43ac-a649-e5675f0f7680 
May 7, 2022 1:51 PM  Filters: 
May 7, 2022 1:51 PM  41 
May 7, 2022 1:51 PM  RunspaceHost 
May 7, 2022 1:51 PM  26 
May 7, 2022 1:51 PM  Runspace Bound Values 
May 7, 2022 1:51 PM  41 
May 7, 2022 1:51 PM  Key   : fcd7d79e-3276-4f04-b34e-5156659bf7ff 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 0de87a1f-1e4f-4acc-ac82-7366947adc10 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : ecfb7725-e7e3-4a8b-b861-17ad674806f4 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : d1538737-31c9-4fa7-8645-5b75f4c02b0e 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 1296c1a6-5e1a-42fa-a9e0-2b15e43d1046 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 79633b88-b5b3-4d87-93b0-a4d65bce17a4 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 64e42ae8-3ef5-46a3-96b6-0d3e1bea7219 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 75b3fac0-322f-4049-91bd-e988f67116ad 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : f30b3343-731f-4a00-a41e-ae0a87846454 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 25b00a6c-9bb4-46fa-910a-c822f6208934 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cf789f83-325f-44d5-a637-f97c6066edec 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 6dfb8182-f7e8-4fc1-92a7-3e6d30c2763e 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : a07a056e-4be2-4918-869e-9639bd71b74d 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 82f5e870-a014-4597-a8bd-ec612829bd47 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 81366e3c-5f30-46c7-bdea-e05d4bf0e7fa 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 642c1e56-c138-40b5-b5db-6dfef0414834 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 78b4ad84-b746-426b-a515-71e5cf53c8df 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : e7d9dea2-f69b-428d-8166-628402a973bd 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : fd4452af-04be-4d1e-a792-222d726dfd86 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : c8e849b6-91f1-468b-aee1-1dd7bfefa8f0 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 2e00e732-8ed5-40cb-8713-0fee9ef96705 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : e5446703-dffd-45df-b0ae-e0a87033b6d9 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 4ac353b7-a2e8-488d-97cb-9c3a35c6a8ad 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cb0c535e-0020-4911-b789-1171e5f220e2 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : bc0fac40-0494-4b7c-913f-cfb894c3ba56 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : f609b22c-ebb7-4791-98d6-808762e747ad 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : a991a3d7-12bc-4949-bf62-d65e669fd784 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 1b83092c-eb78-46d3-8dd0-0c4e86691e95 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : b0bb3931-c447-4417-b4b2-1658f3eb14c5 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : fe20193c-8631-4c45-b46f-8656bca3a65c 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 06b29d3b-c387-43ac-a649-e5675f0f7680 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 8062c65f-0c33-44fc-9a84-21b523a547e9 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : ee2a9980-21e6-4acc-82db-3fec7d7a2666 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cf8b80b1-307e-4dc2-b4d6-af2382fce171 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 2f420e39-9bd2-43a1-931a-1cc97c66d71b 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 31cfff54-d258-4453-b671-6fbfbbfae7d5 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : ab98ff2a-559f-441b-a856-16bad5c0f6c0 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cff3a299-a1ea-47af-b339-8df4d14d71b6 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 12ed3a56-1234-46c7-967f-0332fd7cb322 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : a11f949d-2910-4ea6-b656-cd42f8c97e76 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 283f47e2-367c-4938-8f2b-0d3484a52192 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Script Blocks 
May 7, 2022 1:51 PM  12 
May 7, 2022 1:51 PM  Log Queue: 
May 7, 2022 1:51 PM  2 
```

The list of FilterContainer items in the RunspaceBoundValue collection continues to grow and grow until all the memory is consumed. I'm invoking scripts using:

```
var powershell = PowerShell.Create()
powershell.Runspace = runspace; 
powershell.AddScript("Test")
powershell.BeginInvoke()
```

If you have any suggestions for where I should start looking around, I'm all ears!

### PR DESCRIPTION
**Pull request by adamdriscoll**
This fixes #518. I do not see the memory increase indefinitely with this change. PowerShell Universal sits at about 900 MB and a memory profile shows that we have 1024 PSF log messages in the log queue but no excess of runspace bound values. 

The memory will grow until the runspace bound values are cleaned up every 15 minutes. 

The only reason I realized this was the issue was in Visual Studio when I was looking at the RunspaceBoundValueGeneric, the PurgeExpired method had 0 references. After making this change, you can see it has two. 

image

I'm also thinking of adding a setting to more aggressively run the purge but in the meantime we can suggest running it manually like this. 

```powershell
$MethodInfo = [PSFramework.Runspace.RunspaceHost].GetMethod('CleanupRunspaceBoundVariables', ([System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::NonPublic))
$MethodInfo.Invoke($null, @($null, $null))
```

### CODE REVIEW

**Comment by Callidus2000** [comment]
Hi Adam,
anything additional to to in order to test a module change within the CS code? I ran
```
git clone https://github.com/adamdriscoll/psframework.git AdamsPSF
cd .\AdamsPSF\
.\build\vsts-build.ps1 -LocalRepo
```
and deployed the created Package to my server, memory behavior seems not to have changed. Taking a look at the publish folder it's looking like the PSFramework.dll is still old and therefor not reflecting the changes.

**Comment by adamdriscoll** [comment]
I was sure if I was supposed to check those in so I did. The updated DLLs are now part of this branch.

**Comment by Callidus2000** [comment]
If the DLL should be included is a question just for Fred :smirk:, as he has to decide how a contributor should be able to build his/her development build package version. As I'm also a happy user of his PSModuleDevelopmant module I know the general structure of his modules, but `vsts-build.ps1` ignores the dll build...

Long talk short: THX for including the compiled DLL. What I did for testing:

- Pulled your repo
- build the *.nupkg package from it
- threw it into the module repo of my internal server
- stopped the web-site and the application pool
- deleted the old PSF installation directory
- installed your version
- restarted the IIS components
- let some time pass

I don't know why but the first 9h the memory was still leaking, then some cleanup/automatic restart/refresh seems to have kicked in and since Yesterday 17:00 the memory is rising only a small amount...

image

Your fix did help a lot from my perspective.

**Comment by FriedrichWeinmann** [comment]
Heya,
sorry about the delay and thank you so much for finding this!

> I wasn't sure if I was supposed to check those in, but now I did. The updated DLLs are now part of this branch.

Yeah, I check the dll in for some unintuitive reason:
There's a couple of reasons, but the key one is convenience - I need it built locally anyway for local testing and generally I'm the only person messing the the C# bits, so it never was an issue.
It also makes it easier for users to clone my repo for internal use, when they don't have to build it (they still can build it anyway, if it matters to them).
So ... part laziness, part convenience, part audience targeting and part laziness.

Oh, and on the topic of being lazy:

```powershell
# Insufficiently Lazy:
$MethodInfo = [PSFramework.Runspace.RunspaceHost].GetMethod('CleanupRunspaceBoundVariables', ([System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::NonPublic))
$MethodInfo.Invoke($null, @($null, $null))

# Better
$methodInfo = [PSFramework.Utility.UtilityHost]::GetPrivateStaticMethod([PSFramework.Runspace.RunspaceHost], 'CleanupRunspaceBoundVariables')
$methodInfo.Invoke($null, @($null, $null))

# Best (Coming in the next release)
[PSFramework.Utility.UtilityHost]::InvokePrivateStaticMethod('CleanupRunspaceBoundVariables', [PSFramework.Runspace.RunspaceHost], $arguments)
```

The UtilityHost class contains plenty reflection tools :)

Again, thanks for all the effort.
Will wrap this up together with a few other tweaks and release it tonight

**Comment by FriedrichWeinmann** [comment]
Oh, also adding a new configuration setting to this release:

```text
PSFramework.Runspace.RunspaceBoundValue.CleanupInterval
```

With that you'll be able to adjust the cleanup interval to however frequently you want it to run, without having to mess with interna.
Also, this too is going to be a thing, just in case:

```powershell
[PSFramework.Runspace.RunspaceHost]::PurgeAllRunspaceBoundVariables()
```

**Pull request merged**
